FROM oven/bun:1 AS base
WORKDIR /app

# Install dependencies
FROM base AS deps
COPY package.json ./
COPY lab/server/package.json ./lab/server/
COPY lab/app/package.json ./lab/app/
COPY manager/server/package.json ./manager/server/
COPY lib/auth/package.json ./lib/auth/
COPY lib/db/package.json ./lib/db/
COPY lib/html/package.json ./lib/html/
RUN bun install

# Build the app
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules

COPY . .
RUN bun install
# Build frontend
ARG VITE_MANAGER_URL
ENV VITE_MANAGER_URL=$VITE_MANAGER_URL
RUN bun run --filter "lab-app" build

# Production image
FROM base AS runner
ENV NODE_ENV=production

COPY --from=builder /app/lib ./lib
COPY --from=builder /app/lab/server ./lab/server
COPY --from=builder /app/lab/app/dist ./lab/app/dist
COPY --from=builder /app/node_modules ./node_modules

WORKDIR /app/lab/server
EXPOSE 3001
CMD ["bun", "run", "src/index.ts"]
